import type { EndpointEvent, ForensicArtifact, ForensicArtifactInput } from "../schemas/endpoint.schema";
import { createId } from "../utils/ids";

function artifact(caseId: string, type: ForensicArtifact["type"], source: string): ForensicArtifact {
  return {
    id: createId("forensic_artifact"),
    caseId,
    type,
    source,
    collected: false,
    chainOfCustody: ["Generated by endpoint forensic checklist service."]
  };
}

export function buildArtifactChecklist(caseId: string, events: EndpointEvent[]): ForensicArtifact[] {
  const signals = new Set(events.flatMap((event) => event.riskSignals));
  const artifacts = [
    artifact(caseId, "process_logs", "Windows Event ID 4688 or EDR process telemetry"),
    artifact(caseId, "user_session", "Interactive logon and session context for affected user and host")
  ];

  if (signals.has("encoded_powershell")) {
    artifacts.push(artifact(caseId, "script_block_logs", "PowerShell script block and module logs for the affected host"));
    artifacts.push(artifact(caseId, "edr_alert", "Endpoint alert and prevention timeline for encoded PowerShell activity"));
  }

  if (signals.has("suspicious_office_child") || signals.has("office_spawned_interpreter")) {
    artifacts.push(artifact(caseId, "prefetch", "Prefetch or application execution artifacts for Office and child processes"));
  }

  if (events.some((event) => event.network.dstIp)) {
    artifacts.push(artifact(caseId, "network_connection", "Endpoint network connection telemetry around suspicious process execution"));
  }

  return artifacts;
}

export function buildForensicArtifactsFromInput(caseId: string, input: ForensicArtifactInput[]): ForensicArtifact[] {
  return input.map((item) => ({
    id: createId("forensic_artifact"),
    caseId,
    type: item.type,
    source: item.source,
    collected: item.collected,
    hash: item.hash,
    storageRef: item.storageRef,
    chainOfCustody: item.chainOfCustody
  }));
}
